# Generated by Django 3.1 on 2020-08-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200817_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, to='auctions.Auction'),
        ),
    ]
